# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - YasiruRamosh

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_6e7c81a7d3204403ad9217c170389be7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_aa40fcddf9554a8aa8e0ea4dff231fbb }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_6e7c81a7d3204403ad9217c170389be7 }}/ramosh99/onebilliontech-server:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'YasiruRamosh'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f4e3c8489685410595843dc09627d4e6 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_6e7c81a7d3204403ad9217c170389be7 }}/ramosh99/onebilliontech-server:${{ github.sha }}'